name: Deploy QLKS App

on:
  push:
    tags:
      - 'qlks/v*'  
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '8.0'  # Phiên bản .NET
      CONFIGURATION: 'Release'
      CONNECTION_STRING: "Data source=(localDB)\\MSSQlLocalDB;AttachDbFilename=|DataDirectory|\\QuanLyKhachSan.mdf;Initial Catalog=DefaultConnection;Integrated Security=True"

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build Project
      - name: Build QLKS Application
        run: dotnet build --configuration ${{ env.CONFIGURATION }}

      # Apply EF Migrations
      - name: Apply EF Migrations
        run: dotnet ef database update
        env:
          DOTNET_ENVIRONMENT: "Production"
          ConnectionStrings__DefaultConnection: ${{ env.CONNECTION_STRING }}

      # Publish with Self-Contained and Single File
      - name: Publish QLKS Application
        run: |
          dotnet publish -c ${{ env.CONFIGURATION }} \
          -r win-x64 --self-contained true \
          -p:PublishSingleFile=true -p:PublishTrimmed=true \
          -o ./publish

      # Upload artifact for release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qlks-app
          path: ./publish/

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./publish/**
