name: "Quan Ly Khach San"

on:
  push:
    tags:
      - "qlks/v*"

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true  

      - run: dir /s  

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore ${{ github.workspace }}/QuanLyKhachSan/QuanLyKhachSan.csproj
  
      - run: dotnet build ${{ github.workspace }}/QuanLyKhachSan/QuanLyKhachSan.csproj -c Release --no-restore
  
      - run: dotnet publish ${{ github.workspace }}/QuanLyKhachSan/QuanLyKhachSan.csproj -c Release -o publish --self-contained -r win-x64 -p:PublishSingleFile=true
