name: Deploy QLKS App

on:
  push:
    tags:
      - 'qlks/v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '7.0'
      CONFIGURATION: 'Release'
      CONNECTION_STRING: "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=QLKS;Integrated Security=True;"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Apply EF6 Migrations
        run: powershell ./update-database.ps1
        env:
          ConnectionStrings__DefaultConnection: ${{ env.CONNECTION_STRING }}

      - name: Publish QLKS Application
        run: |
          dotnet publish -c ${{ env.CONFIGURATION }} `
          -r win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -o ./publish

      # Zip published files
      - name: Zip Published Files
        run: |
         mkdir ./artifacts
         cd ./publish
         $tag = "${{ github.ref_name }}"
         $tag = $tag -replace '/', '_'
         Compress-Archive -Path * -DestinationPath ../artifacts/QLKS_$tag.zip


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qlks-app
          path: ./publish/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./publish/**
