name: Build and Release QLKS

on:
  push:
    tags:
      - 'qlks/v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore QuanLyKhachSan.sln

      # Build Application
      - name: Build QLKS Application
        run: dotnet build QuanLyKhachSan.sln -c Release --no-restore

      # Publish Application
      - name: Publish QLKS Application
        run: |
          dotnet publish QuanLyKhachSan.sln -c Release -r win-x64 \
          --self-contained true \
          --publish-single-file true \
          /p:PublishTrimmed=false \
          /p:IncludeNativeLibrariesForSelfExtract=true \
          -o ./publish

      # Zip published files
      - name: Zip Published Files
        run: |
          mkdir ./artifacts
          cd ./publish
          Compress-Archive -Path * -DestinationPath ../artifacts/QLKS_v${{ github.ref_name }}.zip

      # Upload artifact to GitHub
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QLKS_v${{ github.ref_name }}
          path: ./artifacts/QLKS_v${{ github.ref_name }}.zip

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./artifacts/QLKS_v${{ github.ref_name }}.zip
